name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Azure using the Azure CLI
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Login to ACR
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # Step 4: Build the Docker image (fixed path)
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/mydotnetapp:${{ github.sha }} -f MyDotNetApp/Dockerfile MyDotNetApp

      # Step 5: Push the Docker image to ACR
      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/mydotnetapp:${{ github.sha }}
  
  deploy-aci:
    name: Verify ACI Login
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Step 1: Login to Azure using the Service Principal for ACI
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Install Kubectl
        run: |
          az aks install-cli

      - name: Deploy to ACI
        run: |
          kubectl apply -f k8s-manifests/deployment.yml

      # Step 2: Verify ACI instance details
     # - name: Verify ACI
       # run: |
        #  az container show \
          #  --resource-group github-action-1 \
          #  --name acrassignment1 \
         #   --query "{Name:name, State:provisioningState, IPAddress:ipAddress.ip}" -o table
