name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Enable manual trigger

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Azure using the Azure CLI
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Login to ACR
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/mydotnetapp:${{ github.sha }} .

      # Step 5: Scan the Docker image (using Trivy for vulnerability scanning)
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.ACR_NAME }}.azurecr.io/mydotnetapp:${{ github.sha }}
          format: table
          exit-code: 0  # Prevent the workflow from failing on scan errors

      # Step 6: Push the Docker image to ACR
      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/mydotnetapp:${{ github.sha }}
